### ISSUE TITLE
Move local_sql_syntax from valve.rs to this project

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/sqlrest.rs#1]
The first feature I'd like this library to have is this code for abstracting over the differences in SQLite and PostgreSQL binding strings:

https://github.com/ontodev/valve.rs/blob/main/src/lib.rs#L1106

**Comment by lmcmicu** [comment]
Implemented. See the commit: https://github.com/ontodev/sqlrest.rs/commit/8bb5e98b2e7f90b4edc880e87a0ed00ac90fe561 and also the corresponding commit in valve.rs: https://github.com/ontodev/valve.rs/commit/67f8c6f7b708d4bcdf05191d45246b2a2120984d
